In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/loan_data.csv")

In [ ]:
df.head()

person_age person_gender person_education  person_income  person_emp_exp  \
0        22.0        female           Master        71948.0               0   
1        21.0        female      High School        12282.0               0   
2        25.0        female      High School        12438.0               3   
3        23.0        female         Bachelor        79753.0               0   
4        24.0          male           Master        66135.0               1   

  person_home_ownership  loan_amnt loan_intent  loan_int_rate  \
0                  RENT    35000.0    PERSONAL          16.02   
1                   OWN     1000.0   EDUCATION          11.14   
2              MORTGAGE     5500.0     MEDICAL          12.87   
3                  RENT    35000.0     MEDICAL          15.23   
4                  RENT    35000.0     MEDICAL          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0                 0.49                         3.0           561   
1                 0.08                         2.0           504   
2                 0.44                         3.0           635   
3                 0.44                         2.0           675   
4                 0.53                         4.0           586   

  previous_loan_defaults_on_file  loan_status  
0                             No            1  
1                            Yes            0  
2                             No            1  
3                             No            1  
4                             No            1

In [ ]:
df.shape

(45000, 14)

In [ ]:
#drop unnecessary columns
df.drop(columns=['person_age','person_gender','person_education','person_home_ownership','loan_intent','previous_loan_defaults_on_file'],inplace=True)


In [ ]:
df.head()

person_income  person_emp_exp  loan_amnt  loan_int_rate  \
0        71948.0               0    35000.0          16.02   
1        12282.0               0     1000.0          11.14   
2        12438.0               3     5500.0          12.87   
3        79753.0               0    35000.0          15.23   
4        66135.0               1    35000.0          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  loan_status  
0                 0.49                         3.0           561            1  
1                 0.08                         2.0           504            0  
2                 0.44                         3.0           635            1  
3                 0.44                         2.0           675            1  
4                 0.53                         4.0           586            1

In [ ]:
#drop missing values
df.dropna(inplace=True)

In [ ]:
X = df.drop(columns=['loan_status'])
y = df['loan_status']

In [33]:
#scaling the values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [ ]:
#encoding
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [ ]:
# splitting the dataset
X_train, X_test, y_train, y_test = train_test_split( X, y, train_size=0.89, shuffle=True, random_state=11)


# **DEFINING A LOGISTIC REGRESSION CLASS:**

In [ ]:
class Regression():
  def __init__(self,learning_rate,iterations):

    self.learning_rate = learning_rate
    self.iterations = iterations

  def fit(self,X,Y):

    self.m, self.n = X.shape
    self.W = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    for i in range(self.iterations):
      self.update_weights()

    return self

  def update_weights(self):

    A = 1 / (1+ np.exp (- ( self.X.dot( self.W ) + self.b )))
    tmp = A - self.Y.T
    tmp = np.reshape( tmp, self.m )
    dW = np.dot( self.X.T, tmp/self.m )
    db = np.sum(tmp)/self.m

    self.W = self.W-self.learning_rate *dW
    self.b = self.b-self.learning_rate *db

    return self

  def predict(self,X):

    Z = 1 / ( 1 + np.exp( -( X.dot( self.W ) + self.b )))
    Y = np.where( Z>0.5, 1, 0 )

    return Y

# TRAINING THE MODEL:


---


**first_model = model trained using scratch**


---


**second_model = model trained using Scikit Learn Library**


---







In [ ]:
first_model = Regression(learning_rate=0.01, iterations=1000)
first_model.fit(X_train, y_train)
second_model = LogisticRegression()
second_model.fit(X_train, y_train)

LogisticRegression()

# CALCULATING THE ACCURACY

In [ ]:
y_pred_1 = first_model.predict(X_test)
y_pred_2 = second_model.predict(X_test)
cc_1=0
cc_2=0

In [25]:
print(y_pred_1)
print(X_test)

[0 0 0 ... 0 0 0]
[[0.00556267 0.016      0.36231884 ... 0.40909091 0.07142857 0.32608696]
 [0.00520342 0.         0.1884058  ... 0.22727273 0.14285714 0.5826087 ]
 [0.01151977 0.024      0.13043478 ... 0.09090909 0.07142857 0.54130435]
 ...
 [0.01737079 0.         0.35072464 ... 0.13636364 0.         0.56086957]
 [0.02075571 0.         0.12463768 ... 0.04545455 0.25       0.61086957]
 [0.00407785 0.         0.27536232 ... 0.40909091 0.07142857 0.59347826]]


In [ ]:
c=0
for c in range(np.size(y_pred_1)):

  if y_test[c] == y_pred_1[c]:
    cc_1 +=1
  if y_test[c] == y_pred_2[c]:
    cc_2 +=1
  c+=1

In [ ]:
print( "Accuracy on test set by first model  :  ", (cc_1 / c) * 100)
print( "Accuracy on test set by second model (sklearn model)   :  ", (cc_2 / c) * 100)


Accuracy on test set by first model  :   77.55555555555556
Accuracy on test set by second model (sklearn model)   :   82.76767676767676


Thus we can conclude that the sklearn model is slightly more accurate than out model :)


---



# ENTER YOUR DETAILS TO KNOW YOUR LOAN STATUS :)

In [34]:
X_input = []
X_input.append(input("ENTER person_income: "))
X_input.append(input("ENTER person_emp_exp: "))
X_input.append(input("ENTER loan_amnt: "))
X_input.append(input("ENTER loan_int_rate: "))
X_input.append(input("ENTER loan_percent_income: "))
X_input.append(input("ENTER cb_person_cred_hist_length: "))
X_input.append(input("ENTER credit_score: "))

X_input = np.array(X_input).reshape(1, -1)
X_scaled = scaler.transform(X_input)

y_input = first_model.predict(X_scaled)

if y_input[0] == 1:
    print("LOAN APPROVED :)")
else:
    print("LOAN NOT APPROVED :(")

ENTER person_income: 87656
ENTER person_emp_exp: 0
ENTER loan_amnt: 45678
ENTER loan_int_rate: 6
ENTER loan_percent_income: 60
ENTER cb_person_cred_hist_length: 2
ENTER credit_score: 567
LOAN NOT APPROVED :(
